### ISSUE TITLE
[Feature Request] Add errors on sign-in page

### ISSUE THREAD

**Issue by ThePolishLemon** [SimonB50/librusek#4]
Please add a few errors and/or visual cues mainly for:
- Wrong username/password
- Unresponsive api
- Potential rate limit (usually these can be fixed by doing a recaptcha on synergia's site)

**Comment by SimonB50** [comment]
All of the mentioned problems for the sign-in page have been fixed with [9d80aff](https://github.com/SimonB50/librusek/commit/9d80aff636add981dae89507055470d3da61bd97).
Sadly, captcha will require user to log-in through Synergia page, since there is no way of implementing recaptcha in the app.
